# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Newman API based

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-apis:
    runs-on: ubuntu-latest
    steps:
    - name: Run Newman
      uses: matt-ball/newman-action@v1.0.4
      with:
        apiKey: ${{ secrets.POSTMAN_API_KEY }}
        collection: "22874692-840e614a-d38c-4a05-b152-0701fab17fba"
